name: Floodgate Repo Sync

on:
  push:
    branches:
      - stage
      - main
  workflow_dispatch:
    inputs:
      syncBranch:
        description: 'Branch to sync'
        required: true
        default: 'stage'
        type: choice
        options:
          - 'stage'
          - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e
        with:
          app-id: ${{ secrets.FG_SYNC_APP_ID }}
          private-key: ${{ secrets.FG_SYNC_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "milo-pink"

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
          ref: ${{ inputs.syncBranch || github.ref_name }}

      - name: Clone Floodgate Repository and Checkout Selected Branch
        run: |
          git clone https://github.com/adobecom/milo-pink.git ../milo-pink
          cd ../milo-pink
          git checkout $FG_SYNC_BRANCH
          echo "milo-pink branch"
          git branch
          cd ../milo
          echo "milo branch"
          git branch
        env:
          FG_SYNC_BRANCH: ${{ inputs.syncBranch || github.ref_name }}

      - name: Overwrite floodgate repo files with latest from source repo
        run: |
          rsync -av --exclude='fstab.yaml' --exclude='.github' --exclude='.kodiak' --exclude='.git' --exclude='.idea' --exclude='.husky' --exclude='.vscode' --exclude='tools/sidekick/config.json' ./ ../milo-pink/

      - name: Commit and Push Changes to Floodgate Repository
        run: |
          cd ../milo-pink
          echo "milo-pink branch"
          git branch
          git config user.email "$FG_SYNC_BOT_EMAIL"
          git config user.name "$FG_SYNC_BOT_NAME"
          git status
          if [[ -n $(git status -s) ]]; then
            git remote set-url origin https://oauth2:$GITHUB_TOKEN@github.com/adobecom/milo-pink.git
            git remote -v
            git add .
            git commit -m "Syncing milo to milo-pink"
            git push origin $FG_SYNC_BRANCH --force
            echo ":heavy_check_mark: Syncing branch $FG_SYNC_BRANCH on milo to milo-pink completed successfully." >> $GITHUB_STEP_SUMMARY
          else
            echo ":heavy_minus_sign: No changes detected on branch $FG_SYNC_BRANCH, nothing to sync." >> $GITHUB_STEP_SUMMARY
          fi
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          FG_SYNC_BOT_EMAIL: ${{ secrets.FG_SYNC_BOT_EMAIL }}
          FG_SYNC_BOT_NAME: ${{ secrets.FG_SYNC_BOT_NAME }}
          FG_SYNC_BRANCH: ${{ inputs.syncBranch || github.ref_name }}
