name: Update dependencies

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update file and create PR if needed
      uses: actions/github-script@v7
      with:
        script: |
          const updateDependency = require('./.github/workflows/update-script.js')
          updateDependency({
            github, 
            context, 
            title: '[AUTOMATED-PR] Update imslib.min.js dependency', 
            path: 'https://auth.services.adobe.com/imslib/imslib.min.js',
            branch: 'update-imslib',
            scriptPath: './libs/deps/imslib.min.js'
          })
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
